### ISSUE TITLE
Add ZTransducer to convert from stream of Char to stream of A

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-json#10]
The `JsonDecode` type class can have a method `decodeJsonTransducer`, which returns a `ZTransducer[Any, Exception, Char, A]`, which decodes character strings to values of type `A`.

**Comment by fsvehla** [comment]
Analogous to #11, this transducer would be limited to sources of either new-line delimited data, or nodes embedded in an array, am I missing some more low-level use case?

**Comment by jdegoes** [comment]
Just those two. If we hit them both for encoding and decoding, we'll have 99% of JSON streaming use cases
