### ISSUE TITLE
Add ZTransducer to encode values of type A into characters streams of JSON data

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-json#11]
The `JsonEncode` type class can have a method `encodeJsonTransducer`, which returns a `ZTransducer[Any, Exception, A, Char]`, which encodes values of type `A` into character strings of JSON data.

**Comment by fsvehla** [comment]
How would this Transducer be used? Multiple pulled values would have to be pushed containing some delimiter to yield characters that represent valid JSON
