### ISSUE TITLE
case class default field values

### ISSUE THREAD

**Issue by dpennell** [zio/zio-json#181]
It would be useful to support default field values when decoding.

```scala
case class Entity(id: Long, description: String = "")

"""{"id":42}""".fromJson[Entity] == Right(Entity(42L, ""))
```

I can provide a PR if needed.

**Comment by fsvehla** [comment]
>> I can provide a PR if needed.

Go for it!

**Comment by cartazio** [comment]
what release is this in? I'm exactly needing this desperately :)

**Comment by fsvehla** [comment]
Only in snapshot releases so far. The Readme in GitHub has a link to the latest snapshot

**Comment by cartazio** [comment]
@fsvehla thx! (though i'm not finding any way to successfully add the snapshots resolver to my project atm :( )
edit: all the documentation online for snapshot resolver stuff seems to not work for me atm

**Comment by cartazio** [comment]
the error i'm seeing (likely my fault) is 
```
[error]   not found: /home/carter/.ivy2/local/dev.zio/zio-json_2.12/0.1+17-974132cc-SNAPSHOT/ivys/ivy.xml

[error]   not found: https://repo1.maven.org/maven2/dev/zio/zio-json_2.12/0.1+17-974132cc-SNAPSHOT/zio-json_2.12-0.1+17-974132cc-SNAPSHOT.pom
```

**Comment by cartazio** [comment]
derp, i was missing a resolver in one sub build. i'll try it agian :)

**Comment by fsvehla** [comment]
This will be included in a non-snapshot release later this week.
