### ISSUE TITLE
no instance for Map[k,v] ?

### ISSUE THREAD

**Issue by cartazio** [zio/zio-json#182]
i've found myself needing to hand write those out for specific types (eg via a list encoding)

**Comment by emarx** [comment]
Were you noticing this when using `Codec` instead of a separate `Encoder` and `Decoder`? If so, I believe I have a fix that I'll submit after my open PR is approved.

**Comment by fsvehla** [comment]
@cartazio We’ll have a snapshot build for you to try in a few hours

**Comment by cartazio** [comment]
This was with derive encoder / decoder.

Interestingly: all the failing deductions were keyed by a Long int.  Though
that could just be an artifact of this code base.

**Comment by cartazio** [comment]
To be clear: I was able to write my own derive for those maps.  I just was
surprised by needing to have instances that mapped them to lists to get a
working instance.

**Comment by fsvehla** [comment]
@cartazio I was able to derive encoders and decoders both using `Derive{Encoder|Decoder}` as well as `DeriveJsonCodec`.

Were you trying to encode a `mutable.Map`?

**Comment by cartazio** [comment]
... you may be correct! This code base has a few mutable maps hidden among the pure ones, and I guess the names for the two are the same in scala. I’ll close this for now and if I find a counter example concretely I’ll open it again.
