### ISSUE TITLE
More performant UUID instances

### ISSUE THREAD

**Issue by fsvehla** [zio/zio-json#193]
- https://github.com/plokhotnyuk/jsoniter-scala/blob/d49fbc5beb35307c357832d171129357fecbcf73/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L2397-L2452
- https://github.com/jchambers/fast-uuid
- https://github.com/47degrees/memeid/pull/192/files#diff-37eacdb4e4316687626b6f7c08f354db2c7704d2544c4543487bd52a879ec61aR111-R139
- https://github.com/openjdk/jdk/commit/ebadfaeb2e1cc7b5ce5f101cd8a539bc5478cf5b

Thanks to @plokhotnyuk for the examples.

**Comment by plokhotnyuk** [comment]
Please add a missing instance of `JsonCodec` for UUID.

**Comment by calvinlfer** [comment]
I will work on this 😸
