### ISSUE TITLE
how to provide a default value for a type when associated field is missing? (aside from new case defaults)

### ISSUE THREAD

**Issue by cartazio** [zio/zio-json#198]
So, https://github.com/zio/zio-json/issues/181 seems to be one way.

*BUT*, my reading of how the `option[A]` implicit is written made me think that if i've marked a field as having that type,
missing field OR Null will both yield None. (which would be VERY VERY helpful for me). I've tried to do that with my code, but its clearly not working.

concretely: in https://github.com/zio/zio-json/blob/974132cc411fd0bf46d9206b68d793a07835c333/zio-json/shared/src/main/scala/zio/json/decoder.scala#L256-L277 

specificaly: 
```scala
  // Option treats empty and null values as Nothing and passes values to the decoder.
  //
  // If alternative behaviour is desired, e.g. pass null to the underlying, then
  // use a newtype wrapper.
  implicit def option[A](implicit A: JsonDecoder[A]): JsonDecoder[Option[A]] =
    new JsonDecoder[Option[A]] {
      private[this] val ull: Array[Char] = "ull".toCharArray

      override def unsafeDecodeMissing(trace: List[JsonError]): Option[A] =
        Option.empty

      def unsafeDecode(trace: List[JsonError], in: RetractReader): Option[A] =
        (in.nextNonWhitespace(): @switch) match {
          case 'n' =>
            Lexer.readChars(trace, in, ull, "null")
            None
          case _ =>
            in.retract()
            Some(A.unsafeDecode(trace, in))
        }
    }

```

so in my code, i wrote: 

```scala 
 implicit def decoder[A](implicit decoding : JsonDecoder[A]): JsonDecoder[Assumed[A]]
            = JsonDecoder.option[A].map(x =>
                  x match {
                      case None => MissingAssumed[A]()
                      case Some(v )=> FoundAssumed[A](v) }
```
yet i'm consistently seeing the `.fieldName(missing)` error from the parser for a field that has the type `Assumed[A]`

is this an error in my part, or that of the parser or the comments?

**Comment by cartazio** [comment]
to be concrete, i've a type

```scala 
case class Example(
  fieldName : Assumed[Bool]
)
```
(which is essentially an `Option[Bool]`),
i want to just have things be populated with my analogue of `None` when the field is missing.

I *thought* that provided instance for option handles this, but my experiments seem to point to know.

The default missing value support in current snapshot releases helps, but makes what would otherwise be a type directed definition turn into hand providing defaults across  hundreds of fields in many dozens of case classes.

Am i doing something wrong or is this just not working?

**Comment by cartazio** [comment]
i guess phrased different, #181 provides a way to do defaults `top down` from the field definition. I'm hoping theres a `bottom up` mechanism using the right type instances for the decoders!

**Comment by cartazio** [comment]
cc @fsvehla  :)

**Comment by fsvehla** [comment]
Correct me if I’ve misunderstood the requirements (a more complete example would be helpful in this case), but is this not what you’re looking for?

```scala
test("carazio") {
  import zio.json._

  sealed trait Assumed[+A]

  object Assumed {
    case object MissingAssumed        extends Assumed[Nothing]
    case class  FoundAssumed[A](v: A) extends Assumed[A]
  }

  implicit def decoder[A](implicit decoding: JsonDecoder[A]): JsonDecoder[Assumed[A]] =
    JsonDecoder.option[A].map {
      case None     => Assumed.MissingAssumed
      case Some(v ) => Assumed.FoundAssumed[A](v)
    }

  case class Example(fieldName : Assumed[Boolean])
  implicit val exampleDecoder: JsonDecoder[Example] = DeriveJsonDecoder.gen[Example]

  assert("""{ "fieldName": null }""".fromJson[Example])(isRight(equalTo(Example(Assumed.MissingAssumed)))) &&
  assert("""{ "fieldName": true }""".fromJson[Example])(isRight(equalTo(Example(Assumed.FoundAssumed(true))))) &&
  assert("""{ "fieldName": false }""".fromJson[Example])(isRight(equalTo(Example(Assumed.FoundAssumed(false)))))
}
```

**Comment by fsvehla** [comment]
@cartazio I see, I’ve missed the requirement of the `null` case.
The derivation code calls the `Option[A]` decoder’s `unsafeDecodeMissing` first, which will throw.

This will require some more careful thinking; The example below should help for your use case though

```scala
test("carazio") {
  import zio.json._
  import zio.json.JsonDecoder.JsonError
  import zio.json.internal.RetractReader
  import scala.annotation.switch

  sealed trait Assumed[+A]

  object Assumed {
    case object MissingAssumed        extends Assumed[Nothing]
    case class  FoundAssumed[A](v: A) extends Assumed[A]
  }

  implicit def decoder[A](implicit A: JsonDecoder[A], opt: JsonDecoder[Option[A]]): JsonDecoder[Assumed[A]] =
    new JsonDecoder[Assumed[A]] {
      override def unsafeDecodeMissing(trace: List[JsonError]): Assumed[A] =
        Assumed.MissingAssumed

      def unsafeDecode(trace: List[JsonError], in: RetractReader): Assumed[A] =
        opt.unsafeDecode(trace, in) match {
          case None    => Assumed.MissingAssumed
          case Some(v) => Assumed.FoundAssumed[A](v)
        }
    }

  case class Example(fieldName : Assumed[Boolean])
  implicit val exampleDecoder: JsonDecoder[Example] = DeriveJsonDecoder.gen[Example]

  assert("""{ "fieldName": null }""".fromJson[Example])(isRight(equalTo(Example(Assumed.MissingAssumed)))) &&
  assert("""{ "fieldName": true }""".fromJson[Example])(isRight(equalTo(Example(Assumed.FoundAssumed(true))))) &&
  assert("""{ "fieldName": false }""".fromJson[Example])(isRight(equalTo(Example(Assumed.FoundAssumed(false))))) &&
  assert("""{ }""".fromJson[Example])(isRight(equalTo(Example(Assumed.MissingAssumed))))
}
```

**Comment by fsvehla** [comment]
I think I’ll have a fix soon as well.

**Comment by cartazio** [comment]
Yea this last example is exactly what I’m hitting/wanting!

**Comment by cartazio** [comment]
I’ll double check and confirm after some rest

**Comment by cartazio** [comment]
style question: i thought implicit resolution worked better when you put them in the associated object `object Assumed` here, and that, aside from namespacing, the actual case/object class instances neednt be in that object?

this example should help me a great deal, i'll try it out and get back to you on that

**Comment by cartazio** [comment]
I think this solves my problem (and works around that bug in the composition of the option parser for now)

thank you very very much! this has made a monstrous migration a teeny bit more humane for me :)

**Comment by fsvehla** [comment]
> style question: i thought implicit resolution worked better when you put them in the associated object object Assumed here, and that, aside from namespacing, the actual case/object class instances neednt be in that object?

The codecs should be in the case object to be picked up by Scala’s implicit resolution.
Enclosung the subtypes of the sealed trait in the case object is a purely stylistic choice.

**Comment by cartazio** [comment]
so i think your second example might be slightly incorrect, 

that 
```
       opt.unsafeDecode(trace, in) match {
          case None    => Assumed.MissingAssumed
          case Some(v) => Assumed.FoundAssumed[A](v)
```

should instead be 
```
       JsonDecoder.option(A).unsafeDecode(trace, in) match {
          case None    => Assumed.MissingAssumed
          case Some(v) => Assumed.FoundAssumed[A](v)
```
?

**Comment by cartazio** [comment]
OR theres a bug in the generic deriving codes, i'm not sure which

**Comment by cartazio** [comment]
looks like i had defined / rederived Option[A] instances and forgot about it

**Comment by fsvehla** [comment]
Those examples should be functionally identical

**Comment by cartazio** [comment]
Yup. You are correct. As I replied to myself: I accidentally derived an overlapping /conflicting instance for option and it was silently getting selected.

**Comment by cartazio** [comment]
hrm, should this all be marked fixed? :)

**Comment by fsvehla** [comment]
Good call.
