### ISSUE TITLE
Conversion from/to JSON AST

### ISSUE THREAD

**Issue by vigoo** [zio/zio-json#201]
Converting the business objects to/from JSON AST is currently not supported due to the design of the library. Still this is something that would be useful in some cases. 

My primary motivation is to be able to reuse an existing YAML implementation such as SnakeYAML to provide yaml support on top of zio-json. Other use cases could be some kind of transformation that is easier to perform on the JSON AST than the original model, etc.

I was thinking of the following implementation:

- Adding an `toJsonAST` in `JsonEncoder` and a `fromJsonAST` to `JsonDecoder`
- Have a default implementation for these which does a roundtrip serialization through a memory buffer
- Provide overrides for the primitive types doing the conversion directly
- Also the derive macro could generate implementations to avoid the performance loss of encoding/decoding during the conversion

Mixing this into the existing encoder and decoder type classes may seem a bit ugly but I think having it automatically available without the need to create additional implicits is a big advantage.

**Comment by fsvehla** [comment]
Love it.
I was having some similar—but less developed—thoughts about the AST.

Adopting the model you’ve outlined above (and carefully implementing it) allows us to reap the benefits of both approaches to JSON codecs.

**Comment by vigoo** [comment]
I'll provide an initial implementation on this weekend
