### ISSUE TITLE
Instances for mutable collections

### ISSUE THREAD

**Issue by fsvehla** [zio/zio-json#205]
I see no reasons why we would not support e.g. `mutable.Map`

**Comment by plokhotnyuk** [comment]
Please add support for other Scala's mutable collections and [arrays](https://github.com/plokhotnyuk/jsoniter-scala/blob/04548e6983997eb891178a92817708b16f178c37/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/ZioJSONEncoderDecoders.scala#L94-L117).

Also, please add missing codecs for immutable collections like `IndexedSeq`, `LinearSeq`, `ListSet`, `TreeSet`
