### ISSUE TITLE
Add section on snapshots to Readme

### ISSUE THREAD

**Issue by fsvehla** [zio/zio-json#206]
- Setting up Sonatype snapshot resolver in SBT
- How to get latest version

**Comment by brbrown25** [comment]
I can assist with this if you'd like.

**Comment by fsvehla** [comment]
@brbrown25 Absolutely!

**Comment by fsvehla** [comment]
@brbrown25 Didn’t seem to work for the stable version: https://zio.github.io/zio-json/docs/overview/overview_index

**Comment by brbrown25** [comment]
@fsvehla very interesting. I had noticed a similar thing at first with it not grabbing the correct tag version. But then I did a fetch and it fixed it. I'll play around with this some more this morning! Also that snapshot version doesn't look correct either.
