### ISSUE TITLE
having difficulty understanding what my custom instances are doing wrong 

### ISSUE THREAD

**Issue by cartazio** [zio/zio-json#209]
Hello again! 
i've a few custom zio parsers to support migrating some code to using zio, and i've run into a real head scratcher which i hope is obvious but isn't to me! 

i've got a "tagless either" (yes, terrible, but needed)
```scala 
case class Union[+A, +B](extract: Either[A, B]){
  def flatMap[AA>: A,C](f : B =>  Union[AA,C]): Union[AA,C]={
    Union(extract.flatMap(f(_).extract))
  }
    def getOrElse[B1 >: B](or: => B1): B1 = this match {
    case Union.URight(b) => b
    case _        => or
  }
 def map[B1](f: B => B1): Union[A, B1] = this match {
    case Union.URight(b) => Union.URight(f(b))
    case _        => this.asInstanceOf[Union[A, B1]]
  }

 def fold[C](fa: A => C, fb: B => C): C = this match {
    case Union.URight(b) => fb(b)
    case Union.ULeft(a)  => fa(a)
  }

def swap: Union[B,A] = this match {
  case ULeft(x)=> URight(x)
  case URight(x) => ULeft(x)
}
}
// should the object be inside the class or vice versa?
  object Union {

    import zio.json._



    implicit def decoder[A, B](implicit decA: JsonDecoder[A], decB: JsonDecoder[B]): JsonDecoder[Union[A, B]] = {
      decA.orElseEither(decB).map(Union(_))
//      decB.orElseEither(decA).map(Union(_).swap)
    }

    implicit def encoder[A, B](implicit decA: JsonEncoder[A], decB: JsonEncoder[B]): JsonEncoder[Union[A, B]] = {
      decA.either(decB).contramap(_.extract)
    }

    object ULeft {
      def apply[A, B](x: A): Union[A, B] = Union(scala.util.Left(x))

      def unapply[A, B](x: Union[A, B]): Option[A] = x match {
        case Union(scala.util.Left(v)) => Some(v)
        case _ => None
      }

    }

    object URight {
      def apply[A, B](x: B): Union[A, B] = Union(scala.util.Right(x))

      def unapply[A, B](x: Union[A, B]): Option[B] = x match {
        case Union(scala.util.Right(v)) => Some(v)
        case _ => None      }
        }
  }



}

```

and then i've been able to boil down several example case classes where this doesnt work well for what i think should be a reasonable  thing 
```scala 


import com.learnvest.util.Union
import org.scalatest.FunSuite
import zio.json._
import zio.json


import java.time.LocalDate


//  def parse

  class TinyExamplesZIOJSON extends FunSuite {

///////// this also works 
//case class Testing1(x: Double
//                    , y : LocalDate ){}
// ////// this works
//    case class Testing1(x: Double
//                        , y : Union[LocalDate,Int] ){}
 //  doesn't work
    case class Testing1(x: Union[String,Double]
                        , y : Union[LocalDate,Int] ){}



    object Testing1 {
      implicit val test1decoder: JsonDecoder[Testing1] =json.DeriveJsonDecoder.gen[Testing1]
    }

    def validateparse[a](in : Either[String,a]):Unit = assert(in match {
      case Left(s) => print(s); false
      case Right(_) => true
    })
    test {
      "does it work "
    } {
//          val input = scala.io.Source.fromResource("example.json").getLines.mkString // for fancier files
      val result = Testing1.test1decoder.decodeJson(" {\n      \"x\": 0.1,\n      \"y\": \"2025-01-01\"\n    }")
        validateparse(result)
    }
  }


```

for legiblity heres the json again 
```json 
{
      "x": 0.1,
      "y": "2025-01-01"
    }
```

**Comment by cartazio** [comment]
i hope i'm doing something very dumb, the error i get is quite hard to work out : `(expected ',' or '}' got '"')`
it seems that adding any sort of string like parser bite me hard?

**Comment by cartazio** [comment]
somehow adding a string flavor to the parser makes it not work any more ?

**Comment by cartazio** [comment]
like, if i were to guess at armchairs length, the string parser fails, but the stream/input possition isn't rolled back correctly and then the second field tries to parse its key rather than value?  (i'm not comfortable enough with scala to really tease that out in the zio json internals mind you).

i'm also likely completely wrong

**Comment by fommil** [comment]
@cartazio I am confused what problem you're trying to solve here. Your `Union` definition is truncated for example.

Firstly you'd probably get more of a response on the discord, as it's more actively monitored.

Secondly, can you write down some examples of your input JSON and the ADT you're trying to recover from that? I see your JSON but I have no idea what you expect that to decode into.

**Comment by cartazio** [comment]
oh, theres a discord? i'll see about hoping on there in a moment
woops, that was supposed to be `case class Union[+A, +B](extract: Either[A, B])` at the top.

for the example 
```scala
   case class Testing1(x: Union[String,Double]
                        , y : Union[LocalDate,Int] )
```

on input 
```json
{
      "x": 0.1,
      "y": "2025-01-01"
    }
```
id like to get 
```scala
val result = Testing1(x = URight(0.1 : Double ), y = ULeft("2025-01-01" :LocalDate))
```
i'm probably butchering the syntax

**Comment by fommil** [comment]
I see. So you want your own alternative to the default Either that winds back on failure.

Have a look at `Decoder.orElseEither` which has the symbolic alias `<+>`. Note that introducing backtracking will impact performance; but if you're coding to a spec then there's not much you can do.

**Comment by cartazio** [comment]
if you look that, that *is my* instance for `Union`, see the snippet where i write 
```scala

  implicit def decoder[A, B](implicit decA: JsonDecoder[A], decB: JsonDecoder[B]): JsonDecoder[Union[A, B]] = {
      decA.orElseEither(decB).map(Union(_))
//      decB.orElseEither(decA).map(Union(_).swap)
    }
```

unless the deriving stuff ignores that goes through it?

**Comment by cartazio** [comment]
i'm absolutely ok with the performance penalty, i'm confused because i thought i had written it that way! :) 
(however I can help present it for clarity i'm happy to do)

**Comment by fommil** [comment]
ok I didn't see that in the noise. Hmm, interesting. Are you on the latest version? I remember there being some bugs in this in earlier releases.

The magnolia macro should be picking up your instances.

The error message should have more details than what you showed; it should have a `jq` style query showing where the problem was.

**Comment by cartazio** [comment]
i'm currently at 0.1, i'm happy to update to a newer relase if there is one!

the error message for that tiny datatype example is quite terrible `(expected ',' or '}' got '"')`
(on more complicated data types it would give the [edit: jq path] path to the parser position, then give the same error)

**Comment by cartazio** [comment]
i'm glad its an interesting problem, though i wish it was a boring trivial one thats just be being perversely dumb about something :)

**Comment by fommil** [comment]
That should be recent enough. I'll take a closer look.

**Comment by cartazio** [comment]
Cool! Is there gonna be a release with this soon?

**Comment by fsvehla** [comment]
@cartazio Yeah, 0.1.1 today.
