### ISSUE TITLE
Cannot rely on JDK8 Duration.parse 

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-json#214]
Due to a [bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8054978), we may not rely on this method for parsing durations from strings, and should manually implement a workaround.

**Comment by plokhotnyuk** [comment]
[Yet another JDK 8 bug](https://bugs.openjdk.java.net/browse/JDK-8066982), but for `ZonedDateTime.parse`:
```
$ sbt -java-home /usr/lib/jvm/java-8-openjdk-amd64/ console
...
Welcome to Scala 2.13.5 (OpenJDK 64-Bit Server VM, Java 1.8.0_282).
Type in expressions for evaluation. Or try :help.

scala> java.time.ZonedDateTime.parse("2018-03-25T02:30+00:00[Europe/Warsaw]")
val res0: java.time.ZonedDateTime = 2018-03-25T03:30+02:00[Europe/Warsaw]

scala> 

[success] Total time: 27 s, completed Mar 16, 2021 6:28:26 PM
$ sbt -java-home /usr/lib/jvm/java-11-openjdk-amd64/ console
...
Welcome to Scala 2.13.5 (OpenJDK 64-Bit Server VM, Java 11.0.10).
Type in expressions for evaluation. Or try :help.

scala> java.time.ZonedDateTime.parse("2018-03-25T02:30+00:00[Europe/Warsaw]")
val res0: java.time.ZonedDateTime = 2018-03-25T04:30+02:00[Europe/Warsaw]
```

**Comment by plokhotnyuk** [comment]
There is [yet another bug (for `ZonedDateTime.parse`)](https://bugs.openjdk.java.net/browse/JDK-8066982) that was fixed but not back ported to JDK 8. It affects [parsed `ZoneOffset` around DST fall transition](https://github.com/plokhotnyuk/jsoniter-scala/blob/fce69571073f8675e09d61977c9843bae8437018/jsoniter-scala-core/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReaderSpec.scala#L1487-L1496).

**Comment by calvinlfer** [comment]
I will take this please 😸
