### ISSUE TITLE
Wrong float values are parsed for JSON numbers with a long mantissa

### ISSUE THREAD

**Issue by plokhotnyuk** [zio/zio-json#221]
| Input  | Expected Output  | Actual Output  | 
|---|---|---|
|  1.199999988079071 | 1.1999999 | 1.2  |
| 3.4028235677973366e38  |  3.4028235E38 | Infinity  |
| 7.006492321624086e-46  | 1.4E-45  | 0  |

**Comment by fsvehla** [comment]
`float` Lexer ends up calling `BigDecimal.doubleValue.floatValue`. Minimalized:

```
@ new java.math.BigDecimal("1.199999988079071").doubleValue
res27: Double = 1.199999988079071

@ new java.math.BigDecimal("1.199999988079071").floatValue
res28: Float = 1.1999999F

@ new java.math.BigDecimal("1.199999988079071").doubleValue.floatValue
res29: Float = 1.2F
```
