### ISSUE TITLE
option encoder drops values when its null rather than some/none?

### ISSUE THREAD

**Issue by cartazio** [zio/zio-json#238]
Hello! i'm seeing some examples where i'm not emitting fields rather than (as I'd like/expect ) emitting  them with explicit json null. 

could it be that option here isn't handling null? (i've not yet boiled down my examples, but that seems the likely culprit)

```scala
implicit def option[A](implicit A: JsonEncoder[A]): JsonEncoder[Option[A]] = new JsonEncoder[Option[A]] {

    def unsafeEncode(oa: Option[A], indent: Option[Int], out: Write): Unit = oa match {
      case None    => out.write("null")
      case Some(a) => A.unsafeEncode(a, indent, out)
    }

    override def isNothing(a: Option[A]): Boolean = a.isEmpty

    override final def toJsonAST(a: Option[A]): Either[String, Json] =
      a match {
        case Some(value) => A.toJsonAST(value)
        case None        => Right(Json.Null)
      }
  }
```
null isn't handled in the match, and maybe thats  the issue? (cause scala2)

alternatively, somehow its dropping None values somehow silently??

**Comment by cartazio** [comment]
cc @fommil  @fsvehla  any help/wisdom would be extremely appreciated here.

**Comment by fommil** [comment]
that's by design, it's the more common case. If you want different behaviour for `None` you'll need to create a newtype (`extends AnyVal`)

https://github.com/zio/zio-json/blob/develop/zio-json/shared/src/main/scala/zio/json/decoder.scala#L322-L326 is a little bit of docs on the decoder side. On the encoder you'd want to handle `isNothing` differently.

**Comment by cartazio** [comment]
Lest I forget, which tool or mechanism for doing new types is the humane one in 2.12.13 etc?

**Comment by kubukoz** [comment]
I think https://github.com/estatico/scala-newtype/ is the good one. Or doing the manual work... you also have newtypes in zio-prelude I think

**Comment by fsvehla** [comment]
@cartazio Can we close this?

**Comment by cartazio** [comment]
Yup!!
