### ISSUE TITLE
Add Akka http to the list of interop libraries in the documentation

### ISSUE THREAD

**Issue by remiguittaut** [zio/zio-json#246]
Add Akka http to the list of interop libraries in the documentation.

**Comment by fsvehla** [comment]
@remiguittaut You also need to add it to the sidebar: https://zio.github.io/zio-json/docs/interop/interop_index

**Comment by remiguittaut** [comment]
Ha yes, I thought something was off with the menu... Will do.

**Comment by remiguittaut** [comment]
PR done :)
