### ISSUE TITLE
Scala 3: Support default values

### ISSUE THREAD

**Issue by fsvehla** [zio/zio-json#353]
Magnolia doesn’t support default values
https://github.com/softwaremill/magnolia/issues/284

**Comment by mprihoda** [comment]
It seems that default value support for Scala3 in Magnolia just landed a few days ago: https://github.com/softwaremill/magnolia/releases/tag/scala3-v1.1.2

**Comment by carlos-verdes** [comment]
This issue can be closed, to make it work you just need to add this option on scalaC:
```scala
ThisBuild / scalacOptions ++= Seq("-Yretain-trees")
```

Thanks @mprihoda for pointing into that update on Magnolia
