### ISSUE TITLE
Upgrade to ZIO 2

### ISSUE THREAD

**Issue by swoogles** [zio/zio-json#463]
ZIO is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
https://github.com/zio/zio/issues/5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

To assist with the migration, follow this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala

**Comment by fsvehla** [comment]
@swoogles Is this something you’d like to see or want to help out with?

**Comment by swoogles** [comment]
@fsvehla Both :)
We're reviewing the whole ZIO ecosystem currently and identifying the libraries that are heavily used and can most benefit the community by moving to ZIO 2.

@kitlangton is refining the Scalafix rule. We might use  `zio-json` as one of the test projects, if that's agreeable to you.

**Comment by fsvehla** [comment]
@swoogles absolutely!

**Comment by adamgfraser** [comment]
I am working on this.

**Comment by fsvehla** [comment]
Great work, @adamgfraser + @swoogles
