### ISSUE TITLE
Support golden testing

### ISSUE THREAD

**Issue by fsvehla** [zio/zio-json#49]
Investigate how to support _golden testing_

* https://ro-che.info/articles/2017-12-04-golden-tests

**Comment by fsvehla** [comment]
The term in the JS community is [Snapshot testing](https://jestjs.io/docs/en/snapshot-testing)

**Comment by plokhotnyuk** [comment]
ICYMI, [scalatest-json](https://github.com/stephennancekivell/scalatest-json) provides golden testing with different JSON parsers for Scala.

**Comment by ghidei** [comment]
I'm going to work on this! :)

**Comment by jivanic-demystdata** [comment]
@fsvehla We can close this ticket
