### ISSUE TITLE
Pull out integrations into separate modules

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-json#52]
For independent versioning, I think pulling out the integrations into separate modules may make sense. Otherwise they must all proceed in lock-step with every update to each library or to Scala.

**Comment by nathanknox** [comment]
Tentatively claiming this for ZIO Hackathon (assuming I inferred correctly from the Discord. If `zio-json` isn't participating, I'm still interested in contributing). I don't have much background on zio-json but I would like to get involved! If anyone can give me a quick intro that would be awesome.

**Comment by fsvehla** [comment]
@nathanknox Did you make some progress here?

**Comment by fsvehla** [comment]
Simplifies Scala 3 support, working on this.
