### ISSUE TITLE
Interop Modules not published for Scala 3

### ISSUE THREAD

**Issue by rolman243** [zio/zio-json#571]
I'm migrating an existing project from cats and scala 2 to zio 2 and scala 3. The interop modules especially the refined module are not available for scala 3. Because of this I can't even start my build as sbt complains about cross compilation problems.

What is the reason for the interop modules not being published for scala 3?

**Comment by longliveenduro** [comment]
Stumbeled upon the same. 

Also this hack:


Using `"** ("dev.zio"                       %% "zio-json-interop-refined"       % zioJson).cross(CrossVersion.for3Use2_13)"`

causes

`java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-collection-compat, dev.zio:zio-json, dev.zio:zio-stacktracer, dev.zio:izumi-reflect, dev.zio:zio-internal-macros, dev.zio:izumi-reflect-thirdparty-boopickle-shaded, eu.timepit:refined, dev.zio:zio, dev.zio:zio-streams
`

I also tried 
`+ publishLocal`
locally, which published zio-json, zio-golden etc for Scala 3 but not the interop packages. Seems to be a problem with the interop build script part.

UPDATE: 

Looks like dotty is excluded from all interop builds: https://github.com/zio/zio-json/blob/series/2.x/build.sbt#L309
Build for Refined with Scala 3 seems to work fine, so I created a PR: https://github.com/zio/zio-json/pull/772
