### ISSUE TITLE
Equality issue the assertion Num(42.0).value == 42 is false

### ISSUE THREAD

**Issue by dacr** [zio/zio-json#644]
zio-json (0.3.0-rc9) is using `java.math.Decimal instead` of `scala.math.Decimal` which generate some equality issue when we try to compare some numbers such as 42.0 with 42. 
```
scala> Num(42.0).value.getClass.getCanonicalName
val res5: String = java.math.BigDecimal
                                                       
scala> Num(42.0).value == 42
val res6: Boolean = false
                                                       
scala> BigDecimal(42.0) == 42
val res7: Boolean = true
                                                    
scala> BigDecimal(42.0).getClass.getCanonicalName
val res8: String = scala.math.BigDecimal
                                                       
scala> java.math.BigDecimal(42.0) == 42
val res9: Boolean = false
```

A zio-test example which fails with current release : 
```
    test("json AST equality corner cases") {
      val a = """{"a":42}"""
      val b = """{"a":42.0}"""
      for {
        astA <- ZIO.from(a.fromJson[Json])
        astB <- ZIO.from(b.fromJson[Json])
      } yield assertTrue(astA == astB)
    }
```

**Comment by fommil** [comment]
"works as expected" is my take on this. Certainly I designed it this way by intentionally using the Java numeric types and not the Scala ones. 42 is not the same thing as 42.0 in the context of arbitrary precision numerics. The JSON spec models arbitrary precision numbers, not fixed precision. If you want to compare them as (fixed precision) Ints, or Doubles, which may be your intuition, then convert them into those types first. Typically that would be achieved by using the macros to generate encoders/decoders for a specific domain model. Alternatively you could map over the JSON AST and reduce all numbers to their numerical stem scale.

I believe the example comparing `scala.math.BigDecimal` to a literal `Int` is a design flaw in the stdlib. There's a very long thread on the compiler bug tracker about how `scala.math.BigDecimal` is broken in several other ways (especially the constructors which lose precision), but it is far too late to change the semantics now. You might say the opposite and claim that the Java stdlib is the stdlib with the real bug in it, in which case I'd encourage you to raise a bug upstream (whilst also disagreeing with that take).

**Comment by dacr** [comment]
ok I understand, in my particular use case which involve a third party database which give me back 42.0 if I gave it 42 in a json doc, I'll see within my tests to either process the AST to fix this or stop using AST by comparing case class instances

Thank you very much for your feedback, and this great json library :)

**Comment by fommil** [comment]
I think you want to call `stripTrailingZeros`

```scala
new java.math.BigDecimal("42.0").stripTrailingZeros == new java.math.BigDecimal("42")
> true
```

That mapping on the AST would be generally useful, so please consider submitting it back as a PR!


Also, I found the bug reference: https://github.com/scala/bug/issues/9670

(and this whole discussion is yet another example of `==` demonstrating a depressing lack of type safety)

**Comment by dacr** [comment]
Thanks for the suggestion.
- I forked tne project in order to prepare a PR
- I've first added some new tests to reproduce the issue.
- And implemented a first solution based on stripTrailingZeros but it has a huge performance impact at least from unit tests point of view.
- So I think the right solution is to enhance the number parser (numbers.scala -> bigDecimal__) to make it aware of the fact that only 0 are following the dot. I'll try this new approach during the WE.

**Comment by dacr** [comment]
Spent some time of this issue, made some attempts, but Java BigDecimal is also a big mess, very dangerous to use, for example all those assertions are true (I love this one : `assert(JBigDecimal("420.00") != JBigDecimal("420.0"))`) :
```
import zio.*
import zio.json.*
import zio.json.ast.Json.Num
import java.math.BigDecimal as JBigDecimal
import scala.math.BigDecimal as SBigDecimal

assert(SBigDecimal(42.0) == SBigDecimal(42))
assert(JBigDecimal(42.0) == JBigDecimal(42))

assert(SBigDecimal("42.0") == SBigDecimal("42"))
assert(JBigDecimal("42.0") != JBigDecimal("42"))
assert(JBigDecimal("42.0").stripTrailingZeros() == JBigDecimal("42"))
assert(JBigDecimal("420.00") != JBigDecimal("420.0"))

assert("42".fromJson[Num].toOption.get.value == JBigDecimal(42))
assert("42.0".fromJson[Num].toOption.get.value != JBigDecimal(42))
assert("42.0".fromJson[Num].toOption.get.value != JBigDecimal(42.0))
assert("42.0".fromJson[Num].toOption.get.value.stripTrailingZeros() == JBigDecimal(42))
assert("42.0".fromJson[Num].toOption.get.value.stripTrailingZeros() == JBigDecimal(42.0))
assert("42.0".fromJson[Num].toOption.get.value.stripTrailingZeros() != JBigDecimal("42.0"))

assert(JBigDecimal("420.0").stripTrailingZeros != JBigDecimal(420.0)) // Because it is a power of 10 !
assert(JBigDecimal("42.0").stripTrailingZeros == JBigDecimal(42.0)) // Because it is not a power of 10
assert(JBigDecimal("420.0").stripTrailingZeros == JBigDecimal("4.2E+2"))
assert(JBigDecimal("420.0").stripTrailingZeros.toString == "4.2E+2")

assert(JBigDecimal("420.0").setScale(1) != JBigDecimal(420.0))
assert(JBigDecimal("420.0").setScale(1).toString == "420.0")
assert(JBigDecimal("420.0").setScale(0).toString == "420")
```

All comparisons should have been made on the value, and not on the "rendered" value  :(

I close this issue, and no longer use directly Num(x).value really too dangerous in particular when remote systems convert integer numeric type to decimal one...

**Comment by fommil** [comment]
sounds like a very reasonable conclusion.

As somebody who's worked with arbitrary precision for crypto reasons, I actually expect this:

```
assert(JBigDecimal("420.00") != JBigDecimal("420.0"))
```

but I can totally understand why people would not 😆 ... yeah, arbitrary precision is kind of an alien concept. Just one of the many reasons why zio-json encourages people to avoid the JSON AST and to code directly for their business model.

**Comment by plokhotnyuk** [comment]
BEWARE: when used in JSON ASTs without limiting of allowed scale or rounding `java.math.BigDecimal` is vulnerable under DoS/DoW attacks.

Here is how you can burn 4GHz CPU core for ~53 seconds using 13-byte message with subsequent `+` or `-` operations: 
```
andriy@notebook:~/Projects/com/github/plokhotnyuk/jsoniter-scala$ scala
Welcome to Scala 3.1.1 (15.0.7, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                                                                                   
scala> def timed[A](f: => A): A = { val t = System.currentTimeMillis; val r = f; println(s"Elapsed time (ms): ${System.currentTimeMillis - t}"); r } 
def timed[A](f: => A): A
                                                                                                                                                                                                                   
scala> timed(java.math.BigDecimal("1e-100000000"))
Elapsed time (ms): 43
val res0: java.math.BigDecimal = 1E-100000000
                                                                                                                                                                                                                   
scala> timed(java.math.BigDecimal("1e-100000000"))
Elapsed time (ms): 0
val res1: java.math.BigDecimal = 1E-100000000

scala> timed(scala.math.BigDecimal("1e-100000000") + 1)
Elapsed time (ms): 49
val res2: BigDecimal = 1.000000000000000000000000000000000
                                                                                                                                                                                                                   
scala> timed(scala.math.BigDecimal("1e-100000000") + 1)
Elapsed time (ms): 0
val res3: BigDecimal = 1.000000000000000000000000000000000
                                                                                                                                                                                                                   
scala> timed(java.math.BigDecimal("1e-100000000").add(java.math.BigDecimal(1)))
Elapsed time (ms): 53100
val res4: java.math.BigDecimal = 1.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ... large output truncated, print value to show all
```

**Comment by fommil** [comment]
or my favourite one, converting a huge BigDecimal into a BigInteger that causes an OOM https://www.youtube.com/watch?v=3Cz6D8JLSSA
