### ISSUE TITLE
Support automatic derivation of Scala 3 enum

### ISSUE THREAD

**Issue by Al-assad** [zio/zio-json#697]
Hi, `zio-json` does not appear to provide automatic derivation support for `scala-3` enum currently 🥲,  but still requires manual writing of `JsonDecodec` and `JsonEncodec` as follows:

```scala
case class Move(distance: Int, direct: Direction)

given JsonCodec[Move] = DeriveJsonCodec.gen[Move]

enum Direction:
  case North, East, South, West

given JsonEncoder[Direction] = JsonEncoder[String].contramap(_.toString)

given JsonDecoder[Direction] = JsonDecoder[String].mapOrFail { e =>
  Try(Direction.valueOf(e)) match
    case Failure(_) => Left("no matching enum value")
    case Success(v) => Right(v)
}
```
It would be great if the enum could be derived directly with `DeriveJsonCodec.gen` like:
```scala
enum Direction:
  case North, East, South, West

given JsonEncoder[Direction] = DeriveJsonCodec.gen[Direction]
```

**Comment by gurghet** [comment]
Tried this code and works flawlessly, maybe it can be packed into a derive, I'll do it if I get some free time.

**Comment by Al-assad** [comment]
thx, I look forward to it

**Comment by Al-assad** [comment]
It seems that this feature is already supported in zio-json 0.3.0-RC11, and I'll be closing this issue.

**Comment by gurghet** [comment]
Amazeballs

**Comment by timzaak** [comment]
with zio-json 0.3,
```scala
enum TestEnum {
  case A,B
}
object TestEnum {
  given JsonCodec[TestEnum] = DeriveJsonCodec.gen
}

val a = TestEnum.B.toJson
println(a)
println(a.fromJson[TestEnum])

```

The output would be:
```
{"B":{}}
Right(B)
```

If the derive would convert enum to name string or order number?
