### ISSUE TITLE
Custom type decoder/encoder

### ISSUE THREAD

**Issue by daharon** [zio/zio-json#743]
I have a JSON like the following:
```json
{
  "serverTime": 1499827319559
}
```
I want to decode that Unix timestamp to an `Instant`.

With the Kotlin serialization library I would create a custom deserializer from `Long` to `Instant` like so:
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers
And then annotate the `case class` field with `@Serializable(with = UnixTimestampAsInstantSerializer::class)`

How can I do this with the ZIO-JSON library?

**Comment by fsvehla** [comment]
You can override the default `Instant` `JsonDecoder` in a more narrow implicit scope, I’d recommend in the companion object where your `JsonDecoder` of the enclosing case class should be defined.

```scala
import zio.json._
import java.time.Instant

case class Response(serverTime: Instant)

object Response {
  // override default instant decoder
  private implicit val instantDecoder: JsonDecoder[Instant] =
    JsonDecoder[Long].map(Instant.ofEpochMilli)
  
  implicit val responseDecoder: JsonDecoder[Response] =
    DeriveJsonDecoder.gen
}

// Right(Response(2017-07-12T02:41:59.559Z))
print("""{ "serverTime": 1499827319559 }""".fromJson[Response])
```

[Scastie playground link](https://scastie.scala-lang.org/O3YgPhdlTje1BnLmfYWoXA)

**Comment by fsvehla** [comment]
Please reopen if you have any further questions.

**Comment by daharon** [comment]
Thanks, the above works well.

How about the following scenario?

I have the following JSON:
```json
{
  "timezone": "UTC",
  "description": "A description of this object"
}
```
I want to use `JsonDecoder[String].map(java.time.ZoneId.of)`, but _only_ for the `"timezone"` `String`, not for `"description"`.
So I can end up with the following `case class`:
```scala
case class Response(
  timezone: ZoneId,
  description: String
)
```

**Comment by daharon** [comment]
Nevermind.  The following works as I want:
```scala
final case class Response(
  timezone: ZoneId,
  description: String
)

object Response:
  given JsonDecoder[Response] = DeriveJsonDecoder.gen
  given JsonDecoder[ZoneId]   = JsonDecoder[String].map(ZoneId.of)
```
