### ISSUE TITLE
Codec derivation works for scala.Int but not java.lang.Integer

### ISSUE THREAD

**Issue by BalduinLandolt** [zio/zio-json#774]
I'm not sure if that's intended, but it seems that the codecs can only be derived for `scala.Int` but not `java.lang.Integer`:

This works:

```scala
import zio._
import zio.json._

final case class Something(
    value: Int // <-- NB!
)
object Something {
  implicit val codec: JsonCodec[Something] = DeriveJsonCodec.gen[Something]
}

object MyApp extends ZIOAppDefault {
  def run = for {
    _ <- ZIO.unit
    i  = Something(42)
    _ <- Console.printLine(i.toJson)
  } yield ()
}
```

But for this I get an error:

```scala
import zio._
import zio.json._

final case class Something(
    value: Integer // <-- NB!
)
object Something {
  implicit val codec: JsonCodec[Something] = DeriveJsonCodec.gen[Something]
}

object MyApp extends ZIOAppDefault {
  def run = for {
    _ <- ZIO.unit
    i  = Something(42)
    _ <- Console.printLine(i.toJson)
  } yield ()
}
```

The error is: `magnolia: could not find JsonEncoder.Typeclass for type Integer in parameter 'value' of product type Something`

**Comment by fsvehla** [comment]
We don’t define codecs for Java primitives, but you may define them yourselves like this

```scala
implicit val integerCoder: JsonCodec[Integer] = JsonCodec[Int].transform(i => i: Integer, i => i: Int)
```

[Full example @ Scastie](https://scastie.scala-lang.org/B2qujLWzTneJyvtRI3OhxQ)

**Comment by BalduinLandolt** [comment]
fair enough. I was just confused about my IDE suggesting something to me that didn't work. But if that's the intended behaviour, I will close the issue. Thanks for the explanation!
