### ISSUE TITLE
Missing fields lead to error even with default values 

### ISSUE THREAD

**Issue by visox** [zio/zio-json#779]
Following the example in the docs https://zio.github.io/zio-json/docs/overview/overview_decoding

```
case class Entity(id: Long, description: String = "", related: Seq[Entity] = Seq())

object Entity:
  given decoder: JsonDecoder[Entity] = DeriveJsonDecoder.gen[Entity]
```

```
"""{ "id": 42, "related": null }""".fromJson[Entity]
```

crashes with 
```
Cannot json decode because .related(expected '[' got 'n')
```

Note its scala 3
and
lazy val zioJsonV = "0.3.0"

i try some lower version
edit: lower versions didnt help, wonder what i am missing
edit: i also dont see any example in the tests for this (or i am blind)

**Comment by plokhotnyuk** [comment]
[It works as expected for Scala 2](https://scastie.scala-lang.org/plokhotnyuk/ZlVse67sSwSMTsrnf69YUg/4)

**Comment by ex0ns** [comment]
Could you try adding the`"-Yretain-trees"`  flag to scalac ? (only for scala 3)

**Comment by plokhotnyuk** [comment]
@ex0ns Thanks a lot! It helped to port to Scala 3 a benchmark that uses default values: https://github.com/plokhotnyuk/jsoniter-scala/commit/fd7eb96543e1dc454c371daee1a576eff67d8198
