### ISSUE TITLE
Convert over to the standard ZIO project template

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-json#9]
ZIO projects generally use the template [here](https://github.com/zio/zio-project-seed.g8), which has help for deploying and organizing the project. We should switch over to use the template for this project.

**Comment by fsvehla** [comment]
Template is currently broken, see https://github.com/zio/zio-project-seed.g8/issues/27

**Comment by fsvehla** [comment]
This seem to block some other issues, I’m trying it.

**Comment by fsvehla** [comment]
If anyone is running into the issue with zio-project-seed, `89698e2bb341dc54be9f2b2b01bf8519893ddfc5` was a good revision.
