### ISSUE TITLE
Error With Self Referential Type (Children of the same type) 

### ISSUE THREAD

**Issue by ianlintner** [zio/zio-json#917]
Is this supported by ZIO JSON is there an example if it requires some other configuration?

```scala
case class Person(name: String, children: List[Person])
object Person {
  implicit val codec: JsonCodec[Person] = DeriveJsonCodec.gen[Person]
}
```

`Caused by: java.lang.NullPointerException: Cannot invoke "zio.json.JsonCodec.encoder()" because "codec" is null`

**Comment by guizmaii** [comment]
Hey @ianlintner 

Have you tried to define your codec as a `lazy val`?

**Comment by ianlintner** [comment]
That was it. Thank you for the help!
```
implicit lazy val codec: JsonCodec[Person] = DeriveJsonCodec.gen[Person]
```
