### ISSUE TITLE
[Bug] Macro configuration for Scala 3

### ISSUE THREAD

**Issue by vladimir-lu** [zio/zio-json#943]
The macro configuration added in #811 does not support scala 3 due to an underlying magnolia issue: https://github.com/softwaremill/magnolia/issues/296

This required a little digging in the code to find out so I'm opening an issue to raise the visibility.

**Comment by vladimir-lu** [comment]
Not sure if we can't use the straightforward approach in https://github.com/softwaremill/tapir/blob/2b9b7d139405cf87be948d730a4d021bcabacb60/core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala#LL15C31-L15C54 for passing the configuraton?

**Comment by mvv** [comment]
I took a stab at it in #932
